uart_inst	class	38	43
uart_unreset	function	84	90
uart_pin_setup	function	92	99
uart_set_baud	function	107	128
uartinit	function	130	162
cnstart	function	165	165
UART0_IRQ_Handler	function	171	175
UART1_IRQ_Handler	function	177	181
uartopen	function	183	228
uartclose	function	231	243
uartread	function	246	256
uartwrite	function	259	269
uartselect	function	271	281
uartioctl	function	284	298
uartintr	function	300	339
uartstart	function	344	392
uartputc	function	394	427
uartgetc	function	429	447
uartprobe	function	453	488
