#!/bin/sh
set -eu

# Compile scripts/geometry-runtime/optix-ray-runtime.cpp against the OptiX
# headers the optix-dev-headers package installs and the CUDA toolkit, with
# the device programs compiled to PTX for SM89 and embedded in the binary,
# and print the binary's SHA-256, which geometry-service.py records in every
# result. The runtime opens a CUDA context and an OptiX device context, so it
# is never executed here; the OptiX runtime itself is libnvoptix, loaded from
# the driver at run time through optix_stubs.
#
# gpu-ownership: non-gpu-helper; executes no device binary.

usage() {
    printf 'usage: %s OUTPUT_BINARY\n' "$0" >&2
    exit 2
}
[ "$#" -eq 1 ] || usage
output=$1
script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
optix_include=${QWEN_OPTIX_INCLUDE:-/usr/include/optix}
cuda_prefix=${QWEN_CUDA_PREFIX:-/opt/cuda}
host_cxx=${QWEN_HOST_COMPILER:-/usr/bin/g++-15}
cuda_architecture=${QWEN_CUDA_SM:-sm_89}
[ -f "$optix_include/optix.h" ] || { printf 'OptiX headers are absent at %s\n' "$optix_include" >&2; exit 1; }
nvcc=$cuda_prefix/bin/nvcc
[ -x "$nvcc" ] || { printf 'nvcc is absent at %s\n' "$nvcc" >&2; exit 1; }
source_directory=$script_directory/geometry-runtime
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

"$nvcc" -ptx -arch="$cuda_architecture" -std=c++17 -O3 -ccbin "$host_cxx" \
    -I"$optix_include" -I"$source_directory" \
    -o "$work/optix-ray-programs.ptx" "$source_directory/optix-ray-programs.cu"
# the PTX travels inside the binary as one string constant, so the binary's
# digest covers the device programs
python3 - "$work/optix-ray-programs.ptx" "$work/optix-ray-programs-ptx.h" <<'PY'
import sys
ptx = open(sys.argv[1], "rb").read()
with open(sys.argv[2], "w", encoding="ascii") as out:
    out.write("// generated by build-geometry-runtime.sh from optix-ray-programs.cu\n")
    out.write("static const char optix_ray_programs_ptx[] = {\n")
    for i in range(0, len(ptx), 16):
        out.write("    " + ",".join("0x%02x" % b for b in ptx[i:i+16]) + ",\n")
    out.write("    0x00\n};\n")
PY
"$host_cxx" -std=c++17 -O2 -DNDEBUG -Wall -Wextra -o "$output" \
    "$source_directory/optix-ray-runtime.cpp" \
    -I"$optix_include" -I"$cuda_prefix/include" -I"$source_directory" -I"$work" \
    -L"$cuda_prefix/lib64" -lcudart -lcuda -ldl -lpthread \
    -Wl,-rpath,"$cuda_prefix/lib64"
printf 'optix_version=%s\n' "$(sed -n 's/^#define OPTIX_VERSION \([0-9]*\).*/\1/p' "$optix_include/optix.h")"
printf 'ptx_sha256=%s\n' "$(sha256sum "$work/optix-ray-programs.ptx" | cut -d ' ' -f 1)"
printf 'geometry_runtime_sha256=%s\n' "$(sha256sum "$output" | cut -d ' ' -f 1)"
printf 'runtime_execution=not_run reason=build_only\n'
