#!/bin/sh
set -eu

# The image generation UI half of PR D reaches the network through the same
# one-human-approval discipline the web search tool uses, with its own grant
# context and its own synchronous state machine. Grep asserts the structural
# properties against the served file the way
# test-fallback-webui-web-authorization.sh does for the web tools, so the
# gate runs wherever the tree is cloned; the node blocks below exercise the
# pure functions when node is on the path.

if [ "$#" -ne 0 ]; then
    printf 'usage: %s\n' "$0" >&2
    exit 2
fi

script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
fallback_ui=$script_directory/../webui/index.html

# The per-turn Image toggle governs the tool list rather than the request
# text, so a turn run with it off carries no image_generate_image call to propose,
# and a proposal carried over from a turn that offered it reaches no
# generation once the toggle reads off for the current turn.
grep -F '<input type="checkbox" id="image-tools">' "$fallback_ui" >/dev/null
grep -F "const imagePermission = \$('#image-tools').checked;" "$fallback_ui" >/dev/null
if [ "$(grep -c "\$('#image-tools').checked = false;" "$fallback_ui")" -lt 2 ]; then
    printf 'fallback Web UI does not reset the Image toggle at both init and the turn boundary\n' >&2
    exit 1
fi
grep -F 'if (imagePermission) {' "$fallback_ui" >/dev/null
grep -F "const { definition } = await resolveImageTools(requestModel, modelStateGeneration);" \
    "$fallback_ui" >/dev/null
# The served name is composed from the section's own mcpServers key rather than
# written a second time: llama-server serves the `image` server's
# `generate_image` as `image_generate_image` (server-tools.cpp:1814), so a page
# naming the child's bare name reaches find_tool's 404.
grep -F "const IMAGE_MCP_SERVER_NAME = 'image';" "$fallback_ui" >/dev/null
grep -F "const IMAGE_MCP_TOOL_NAME = 'generate_image';" "$fallback_ui" >/dev/null
grep -F 'const IMAGE_TOOL_NAME = `${IMAGE_MCP_SERVER_NAME}_${IMAGE_MCP_TOOL_NAME}`;' \
    "$fallback_ui" >/dev/null
grep -F "if (!imagePermission) {" "$fallback_ui" >/dev/null
grep -F 'The image surface is off for this turn; ${toolName} did not run.' "$fallback_ui" >/dev/null

# The listing is a second, independent read of GET /tools: it reuses
# fetchWebToolListing and webToolDefinition rather than duplicating either,
# and keeps its own cache so a rename of the web tool names does not move it.
grep -F 'async function resolveImageTools(selectedModel, generation) {' "$fallback_ui" >/dev/null
grep -F 'listed = await fetchWebToolListing(selectedModel);' "$fallback_ui" >/dev/null
grep -F "const entry = listed.find(row => row && row.tool === IMAGE_TOOL_NAME);" \
    "$fallback_ui" >/dev/null
grep -F 'const definition = entry ? webToolDefinition(entry) : null;' "$fallback_ui" >/dev/null
grep -F 'function forgetImageTools() {' "$fallback_ui" >/dev/null
if [ "$(grep -c 'forgetImageTools();' "$fallback_ui")" -lt 2 ]; then
    printf 'fallback Web UI does not clear the image tool cache on every model reselection\n' >&2
    exit 1
fi
grep -F 'function findImageCancelToolName(listing) {' "$fallback_ui" >/dev/null

# The dialog names every field the grant is signed over, including the seed
# this page generates when the model omits one.
grep -F "row('prompt'" "$fallback_ui" >/dev/null
grep -F "row('negative prompt'" "$fallback_ui" >/dev/null
grep -F "row('seed'" "$fallback_ui" >/dev/null
grep -F "row('width'" "$fallback_ui" >/dev/null
grep -F "row('height'" "$fallback_ui" >/dev/null
grep -F "row('steps'" "$fallback_ui" >/dev/null
grep -F "row('profile'" "$fallback_ui" >/dev/null
grep -F 'id="image-approve-once"' "$fallback_ui" >/dev/null
grep -F 'id="image-approve-deny"' "$fallback_ui" >/dev/null
grep -F 'generated by this page; the model proposed no seed' "$fallback_ui" >/dev/null

# Randomness is never chosen after authorization: the seed is generated with
# the browser's cryptographic RNG before the dialog opens, not inside the
# approval handler.
grep -F 'function randomSeed() {' "$fallback_ui" >/dev/null
grep -F 'crypto.getRandomValues(new Uint32Array(1))[0];' "$fallback_ui" >/dev/null
seed_line=$(grep -n 'seed = randomSeed();' "$fallback_ui" | cut -d: -f1)
dialog_line=$(grep -n 'function approveImageGeneration' "$fallback_ui" | cut -d: -f1)
if [ -z "$seed_line" ] || [ -z "$dialog_line" ] || [ "$seed_line" -ge "$dialog_line" ]; then
    printf 'fallback Web UI does not generate the seed ahead of the approval dialog\n' >&2
    exit 1
fi

# The grant is signed over hashes of the prompts rather than the prompts
# themselves, and over an aspect and a max-dimension bound rather than the
# raw pixel size, and it names the qwen-image-generate-v1 context and the
# conversation generation.
grep -F "const IMAGE_GRANT_CONTEXT = 'qwen-image-generate-v1';" "$fallback_ui" >/dev/null
grep -F 'async function sha256Hex(text) {' "$fallback_ui" >/dev/null
grep -F 'function aspectRatio(width, height) {' "$fallback_ui" >/dev/null
grep -F 'async function imageGrantFields(fields, languageProfile, conversationGenerationValue) {' \
    "$fallback_ui" >/dev/null
grep -F 'context: IMAGE_GRANT_CONTEXT,' "$fallback_ui" >/dev/null
grep -F 'language_profile: languageProfile,' "$fallback_ui" >/dev/null
grep -F 'image_profile: fields.profile,' "$fallback_ui" >/dev/null
grep -F 'prompt_hash: promptHash,' "$fallback_ui" >/dev/null
grep -F 'negative_prompt_hash: negativePromptHash,' "$fallback_ui" >/dev/null
grep -F 'aspect: aspectRatio(fields.width, fields.height),' "$fallback_ui" >/dev/null
grep -F 'max_dimension: Math.max(fields.width, fields.height),' "$fallback_ui" >/dev/null
grep -F 'max_steps: fields.steps,' "$fallback_ui" >/dev/null
grep -F 'conversation_generation: conversationGenerationValue' "$fallback_ui" >/dev/null
grep -F "fetch(\`\${brokerOrigin()}/grant-image\`, {" "$fallback_ui" >/dev/null

# The grant reaches exactly one call site -- the params object of the one
# POST /tools body the approved generation runs under -- and the transcript
# never carries it.
grep -F 'function imageRequestParams(fields, authorization) {' "$fallback_ui" >/dev/null
# scripts/image-mcp/server.py names the argument profile_id, requires it, and
# refuses any name outside its schema, so the request carries that spelling.
grep -F 'profile_id: fields.profile,' "$fallback_ui" >/dev/null
# Two call sites spend an image grant -- the approved generation in the turn
# dispatch and the approved correction a review proposes -- and each hands it
# straight to imageRequestParams(), which builds the params object of the one
# POST /tools body that generation runs under.
image_grant_reads=$(grep -c 'imageOutcome.authorization' "$fallback_ui")
image_grant_params=$(grep -cE \
    'imageRequestParams\([A-Za-z]+, imageOutcome\.authorization\)' "$fallback_ui")
if [ "$image_grant_reads" -ne 2 ] || [ "$image_grant_params" -ne 2 ]; then
    printf 'fallback Web UI reads an issued image grant outside imageRequestParams()\n' >&2
    exit 1
fi
if grep -E 'answerCall\([^)]*imageOutcome\.authorization' "$fallback_ui" >/dev/null; then
    printf 'fallback Web UI writes an image grant into the transcript\n' >&2
    exit 1
fi

# The synchronous state line reads Approved -> Generating image... -> Image
# complete, or Image failed with the reason read from body.error the way the
# refused, cancelled, and failed MCP statuses all arrive.
grep -F "renderImageState(stateEl, 'Approved');" "$fallback_ui" >/dev/null
grep -F "renderImageState(stateEl, 'Generating image...');" "$fallback_ui" >/dev/null
grep -F "renderImageState(stateEl, 'Image complete');" "$fallback_ui" >/dev/null
grep -F 'renderImageState(stateEl, `Image failed: ${payload.error}`, true);' "$fallback_ui" >/dev/null
grep -F "function parseCompletedImageResult(text) {" "$fallback_ui" >/dev/null
grep -F "if (parsed.status !== 'completed') {" "$fallback_ui" >/dev/null
grep -F 'typeof parsed.sha256' "$fallback_ui" >/dev/null
grep -F 'typeof parsed.provenance_url' "$fallback_ui" >/dev/null

# The client-side wait is the browser's own bound alone and names no
# runtime, image-service, MCP, or router deadline.
grep -F 'const IMAGE_GENERATION_TIMEOUT_MS = 660000;' "$fallback_ui" >/dev/null
grep -F 'setTimeout(() => controller.abort(), IMAGE_GENERATION_TIMEOUT_MS);' "$fallback_ui" >/dev/null

# A Cancel button aborts the fetch and, only when the served tool set names a
# cancel tool, also posts a best-effort cancel; either way the abort itself
# always runs.
grep -F 'async function postCancelBestEffort(cancelToolName, model) {' "$fallback_ui" >/dev/null
grep -F 'if (!cancelToolName) return;' "$fallback_ui" >/dev/null
grep -F 'cancelled = true;' "$fallback_ui" >/dev/null
grep -F 'void postCancelBestEffort(cancelToolName, model);' "$fallback_ui" >/dev/null

# The artifact card fetches the PNG with the page's own credential header
# into a blob URL, because <img src> cannot carry that header, and revokes
# the blob URL when the card is removed. The route is derived from the digest
# rather than taken from the result: image-service.py's provenance_url names
# the `.json` record and its artifact_url names the `.png`, both from the same
# digest, so a page that fetched the provenance route would read the record
# where it wanted the image.
grep -F 'async function loadArtifactBlobUrl(sha256) {' "$fallback_ui" >/dev/null
grep -F '`${artifactOrigin()}/artifacts/${sha256}.png`' "$fallback_ui" >/dev/null
grep -F 'loadArtifactBlobUrl(result.sha256)' "$fallback_ui" >/dev/null
grep -F "mode: 'cors', headers: authHeaders(), signal: controller.signal });" \
    "$fallback_ui" >/dev/null

# The artifact read is bounded and awaited: the turn ends on the artifact, so
# an unresponsive listener answers the model with a tool message rather than
# holding the send button for the generation deadline.
grep -F 'const ARTIFACT_FETCH_TIMEOUT_MS = 60000;' "$fallback_ui" >/dev/null
grep -F 'setTimeout(() => controller.abort(), ARTIFACT_FETCH_TIMEOUT_MS);' \
    "$fallback_ui" >/dev/null
grep -F 'async function renderImageArtifactCard(container, fields, result, lineage) {' \
    "$fallback_ui" >/dev/null
grep -F '  const blobUrl = await loadArtifactBlobUrl(result.sha256);' \
    "$fallback_ui" >/dev/null
grep -F 'await renderImageArtifactCard(artifactContainer, fields, result, lineage);' \
    "$fallback_ui" >/dev/null
grep -F 'const reason = `the artifact did not load: ${error.message || error}`;' \
    "$fallback_ui" >/dev/null
card_line=$(grep -n 'await renderImageArtifactCard' "$fallback_ui" | cut -d: -f1)
complete_line=$(grep -n "renderImageState(stateEl, 'Image complete');" "$fallback_ui" | cut -d: -f1)
if [ -z "$card_line" ] || [ -z "$complete_line" ] || [ "$card_line" -ge "$complete_line" ]; then
    printf 'fallback Web UI reports Image complete before the artifact resolves\n' >&2
    exit 1
fi

# The tool schema states the served profile and its ceilings, so the page reads
# both from the listing it already fetched: an argument above a stated maximum
# is refused before the dialog and before the per-turn budget moves, and the
# profile the grant names is the schema's enum rather than the proposal's
# string.
grep -F 'function imageSchemaBounds(definition) {' "$fallback_ui" >/dev/null
grep -F 'const listedProfiles = properties.profile_id && properties.profile_id.enum;' \
    "$fallback_ui" >/dev/null
grep -F 'function applyImageSchemaBounds(fields, bounds) {' "$fallback_ui" >/dev/null
grep -F 'imageFields = applyImageSchemaBounds(proposedImageFields(calls[index].args), imageBounds);' \
    "$fallback_ui" >/dev/null
grep -F 'exceeds the ${ceiling} this image profile admits' "$fallback_ui" >/dev/null
grep -F 'profile: served || proposedProfile,' "$fallback_ui" >/dev/null
grep -F 'if (fields.profileReplaced) {' "$fallback_ui" >/dev/null
grep -F 'this appliance serves ${fields.profile}, and the grant names the served profile' \
    "$fallback_ui" >/dev/null
bounds_line=$(grep -n 'imageFields = applyImageSchemaBounds' "$fallback_ui" | cut -d: -f1)
budget_line=$(grep -n 'imageBudget.remaining--;' "$fallback_ui" | cut -d: -f1)
if [ -z "$bounds_line" ] || [ -z "$budget_line" ] || [ "$bounds_line" -ge "$budget_line" ]; then
    printf 'fallback Web UI spends the image budget on an out-of-bounds proposal\n' >&2
    exit 1
fi

# A grant the broker refuses ends the dialog and the turn with a tool message.
# The re-enable-and-retry path held `busy` for the whole turn while the model
# waited on a result that never arrived.
grep -F "finish({ decision: 'failed', reason: String(error.message || error) });" \
    "$fallback_ui" >/dev/null
grep -F "if (imageOutcome.decision === 'failed') {" "$fallback_ui" >/dev/null
grep -F 'renderImageState(openImageState(view), `Image failed: ${imageOutcome.reason}`, true);' \
    "$fallback_ui" >/dev/null
grep -F 'The image did not run: ${imageOutcome.reason}.' "$fallback_ui" >/dev/null

# image-service.py binds its artifact listener on an ephemeral port and the
# router proxies none of its routes, so the origin is configured rather than
# resolved against the page, and a page given none says so instead of asking
# the router for a route it does not serve.
grep -F 'function configuredArtifactOrigin() {' "$fallback_ui" >/dev/null
grep -F "searchParams.get('artifacts')" "$fallback_ui" >/dev/null
grep -F 'meta[name="qwen-image-artifacts"]' "$fallback_ui" >/dev/null
grep -F "throw new Error('no artifact listener origin is configured for this page');" \
    "$fallback_ui" >/dev/null
grep -F 'return URL.createObjectURL(blob);' "$fallback_ui" >/dev/null
grep -F 'if (blobUrl) URL.revokeObjectURL(blobUrl);' "$fallback_ui" >/dev/null
grep -F 'function renderImageArtifactCard(container, fields, result, lineage) {' "$fallback_ui" >/dev/null
grep -F "\`sha256 \${result.sha256}\`," "$fallback_ui" >/dev/null
grep -F "\`seed \${fields.seed}\`," "$fallback_ui" >/dev/null
grep -F "\`\${fields.width}x\${fields.height}\`," "$fallback_ui" >/dev/null
grep -F "\`\${fields.steps} steps\`," "$fallback_ui" >/dev/null

# The hash never substitutes for the credential header as an authorization
# query parameter.
if grep -E "loadArtifactBlobUrl\([^)]*\)" "$fallback_ui" | grep -qi 'sha256='; then
    printf 'fallback Web UI carries the artifact hash as a query-string credential\n' >&2
    exit 1
fi

# The retained transcript message names the sha256 and the provenance URL
# alone, never the image bytes and never the grant.
grep -F 'function buildImageToolResultSummary(result) {' "$fallback_ui" >/dev/null
grep -F 'Image generated: sha256 ${result.sha256}, provenance ${result.provenanceUrl}.' \
    "$fallback_ui" >/dev/null

# One image generation is authorized per turn, mirroring the one-search
# budget the web tool enforces.
grep -F 'const IMAGE_GENERATE_BUDGET_PER_TURN = 1;' "$fallback_ui" >/dev/null
grep -F 'const imageBudget = { remaining: IMAGE_GENERATE_BUDGET_PER_TURN };' "$fallback_ui" >/dev/null
grep -F 'if (imageBudget.remaining <= 0) {' "$fallback_ui" >/dev/null
grep -F 'imageBudget.remaining--;' "$fallback_ui" >/dev/null

# A field missing or malformed in the proposal fails the dialog closed rather
# than substituting a value nobody proposed or authored.
grep -F 'function proposedImageFields(argumentText) {' "$fallback_ui" >/dev/null
grep -F "must be a non-empty string" "$fallback_ui" >/dev/null
grep -F 'const requirePositiveInteger = key => {' "$fallback_ui" >/dev/null

# node exercises the pure parsing and hashing functions directly, when node
# is on the path.
if command -v node >/dev/null 2>&1; then
    node -e '
const fs = require("fs");
const crypto = require("crypto");
const source = fs.readFileSync(process.argv[1], "utf8");

function extract(startMarker, endMarker) {
    const start = source.indexOf(startMarker);
    if (start < 0) throw new Error("marker not found: " + startMarker);
    const end = source.indexOf(endMarker, start);
    if (end < 0) throw new Error("end marker not found: " + endMarker);
    return source.slice(start, end);
}

const globalCrypto = {
    getRandomValues: arr => { for (let i = 0; i < arr.length; i++) arr[i] = 42 + i; return arr; },
    subtle: {
        digest: async (_algorithm, bytes) => {
            const hash = crypto.createHash("sha256");
            hash.update(Buffer.from(bytes));
            return hash.digest().buffer;
        }
    }
};
globalThis.crypto = globalCrypto;

eval(extract(
    "const IMAGE_GRANT_CONTEXT = ",
    "// ==== end image generation: proposal parsing and grant"
));
// A second, separate span: the execution/rendering block is a disjoint run
// of function definitions further down the file, so it needs its own
// extract() rather than widening the first span across the intervening
// top-level code (boot(), the toggle resets, the broker-origin wiring) that
// executes immediately on eval and has no DOM in this node sandbox.
eval(extract(
    "function imageRequestParams(fields, authorization) {",
    "// ==== end image generation: execution and rendering"
));

// proposedImageFields: a well-formed proposal with no seed generates one and
// marks it generated; the same proposal with a seed keeps it as proposed.
const noSeed = proposedImageFields(JSON.stringify({
    prompt: "a fox in a field", profile: "sdxs-512", width: 512, height: 512, steps: 4
}));
if (!noSeed.seedGenerated) throw new Error("an omitted seed was not marked generated");
if (!Number.isInteger(noSeed.seed)) throw new Error("a generated seed is not an integer");

const withSeed = proposedImageFields(JSON.stringify({
    prompt: "a fox", profile: "sdxs-512", width: 512, height: 512, steps: 4, seed: 7
}));
if (withSeed.seedGenerated) throw new Error("a proposed seed was overwritten as generated");
if (withSeed.seed !== 7) throw new Error("a proposed seed was not carried through");

for (const malformed of [
    {}, { prompt: "" }, { prompt: "x", profile: "p" },
    { prompt: "x", profile: "p", width: 0, height: 512, steps: 4 },
    { prompt: "x", profile: "p", width: 512, height: 512, steps: 4, seed: -1 },
    { prompt: "x", profile: "p", width: 512, height: 512, steps: 4, seed: 1.5 },
]) {
    let threw = false;
    try { proposedImageFields(JSON.stringify(malformed)); } catch { threw = true; }
    if (!threw) throw new Error("a malformed proposal was not refused: " + JSON.stringify(malformed));
}

// A third span: the tool-discovery block reads the served profile and the
// maxima out of the listing, and it sits above the grant block with top-level
// state between them, so it is extracted on its own.
eval(extract(
    "function imageSchemaBounds(definition) {",
    "let imageToolDefinitionCached"
));

const servedDefinition = { type: "function", function: { name: "image_generate_image",
    parameters: { type: "object", properties: {
        width: { type: "integer", maximum: 512 },
        height: { type: "integer", maximum: 512 },
        steps: { type: "integer", maximum: 4 },
        profile_id: { type: "string", enum: ["sdxs-512-a"] } } } } };
const bounds = imageSchemaBounds(servedDefinition);
if (bounds.profile !== "sdxs-512-a") throw new Error("the schema enum did not name the served profile");
if (bounds.width !== 512 || bounds.height !== 512 || bounds.steps !== 4) {
    throw new Error("the schema maxima were not read: " + JSON.stringify(bounds));
}
const openDefinition = { type: "function", function: { name: "image_generate_image",
    parameters: { type: "object", properties: { profile_id: { type: "string" } } } } };
const openBounds = imageSchemaBounds(openDefinition);
if (openBounds.profile !== null || openBounds.width !== null || openBounds.steps !== null) {
    throw new Error("a schema stating no bound produced one: " + JSON.stringify(openBounds));
}

// applyImageSchemaBounds: the served profile replaces the proposed one and an
// argument above a stated maximum throws the bound it exceeds.
const proposal = proposedImageFields(JSON.stringify({
    prompt: "a fox", profile_id: "product_photography",
    width: 512, height: 512, steps: 4, seed: 42
}));
const applied = applyImageSchemaBounds(proposal, bounds);
if (applied.profile !== "sdxs-512-a") throw new Error("the served profile did not replace the proposed one");
if (!applied.profileReplaced) throw new Error("the replacement went unmarked for the dialog");
if (applied.proposedProfile !== "product_photography") {
    throw new Error("the proposed profile was not retained for the note line");
}
for (const over of [{ width: 1024 }, { height: 768 }, { steps: 30 }]) {
    const key = Object.keys(over)[0];
    let message = null;
    try { applyImageSchemaBounds({ ...proposal, ...over }, bounds); }
    catch (error) { message = error.message; }
    if (message === null) throw new Error("an argument above the schema maximum was admitted: " + key);
    if (!message.includes(key) || !message.includes(String(bounds[key]))) {
        throw new Error("the refusal did not name the argument and its bound: " + message);
    }
}
const unbounded = applyImageSchemaBounds(proposal, null);
if (unbounded.profile !== "product_photography" || unbounded.profileReplaced) {
    throw new Error("a listing stating no profile replaced the proposal anyway");
}

// aspectRatio reduces by the GCD.
if (aspectRatio(1024, 512) !== "2:1") throw new Error("aspectRatio did not reduce 1024x512");
if (aspectRatio(512, 512) !== "1:1") throw new Error("aspectRatio did not reduce a square");

// parseCompletedImageResult reads sha256 and provenance_url from a completed
// status and refuses every other shape, including the three terminal
// non-completed statuses (which the served path answers through
// payload.error instead and never routes through this function).
const completed = parseCompletedImageResult(JSON.stringify({
    status: "completed", sha256: "a".repeat(64), provenance_url: "/artifacts/aaa.png"
}));
if (completed.sha256 !== "a".repeat(64)) throw new Error("sha256 was not read from a completed result");
if (completed.provenanceUrl !== "/artifacts/aaa.png") {
    throw new Error("provenance_url was not read from a completed result");
}
for (const badStatus of ["accepted", "refused", "cancelled", "failed"]) {
    let threw = false;
    try {
        parseCompletedImageResult(JSON.stringify({
            status: badStatus, sha256: "a".repeat(64), provenance_url: "/artifacts/aaa.png"
        }));
    } catch { threw = true; }
    if (!threw) throw new Error("a non-completed status reached parseCompletedImageResult unrefused: " + badStatus);
}

// buildImageToolResultSummary names sha256 and the provenance URL and
// nothing else -- checked structurally since the function itself is the
// single call site that builds the retained transcript message.
const summary = buildImageToolResultSummary({ sha256: "b".repeat(64), provenanceUrl: "/artifacts/bbb.png" });
if (!summary.includes("b".repeat(64)) || !summary.includes("/artifacts/bbb.png")) {
    throw new Error("buildImageToolResultSummary dropped the sha256 or the provenance URL");
}

// imageGrantFields hashes each prompt rather than carrying it in the clear.
imageGrantFields(
    { prompt: "a fox", negative_prompt: "blurry", profile: "sdxs-512", seed: 7, width: 512, height: 512, steps: 4 },
    "lang-profile", 3
).then(grant => {
    if (grant.context !== "qwen-image-generate-v1") throw new Error("grant carries the wrong context");
    if (grant.prompt_hash === "a fox" || grant.prompt_hash.length !== 64) {
        throw new Error("grant does not carry a SHA-256 hex digest for the prompt");
    }
    if (grant.negative_prompt_hash.length !== 64) {
        throw new Error("grant does not carry a SHA-256 hex digest for the negative prompt");
    }
    if (grant.aspect !== "1:1") throw new Error("grant aspect was not derived from width and height");
    if (grant.max_dimension !== 512) throw new Error("grant max_dimension was not the larger side");
    if (grant.conversation_generation !== 3) throw new Error("grant did not carry the conversation generation");
}).catch(error => { console.error(error.message); process.exit(1); });
' "$fallback_ui"
fi

# The vision review (PR F, UI half) runs from idle over one artifact and offers
# the model no executable surface: the request body omits `tools` entirely, the
# reply parses against the closed verdict schema, and the verdict, its
# observations, and any correction stay out of `history`.
grep -F 'const REVIEW_MAX_TOKENS = 400;' "$fallback_ui" >/dev/null
grep -F 'const REVIEW_TIMEOUT_MS = 300000;' "$fallback_ui" >/dev/null
grep -F 'const IMAGE_CORRECTION_CAP = 2;' "$fallback_ui" >/dev/null
grep -F 'function buildReviewRequestBody(visionModel, dataUri, promptHash, constraints) {' \
    "$fallback_ui" >/dev/null
grep -F 'function parseReviewVerdict(reply, names) {' "$fallback_ui" >/dev/null
grep -F 'function reviewCorrectionAdmitted(verdict) {' "$fallback_ui" >/dev/null
grep -F "throw new Error('the reply proposes a tool call against a request carrying no tools');" \
    "$fallback_ui" >/dev/null
grep -F "throw new Error('the reply is not one JSON object');" "$fallback_ui" >/dev/null
# The review request body is composed in one place, and a `tools` key anywhere
# inside it would offer the vision model a surface the design withholds.
if sed -n '/^function buildReviewRequestBody/,/^}/p' "$fallback_ui" \
        | grep -qE '(^|[^a-z_])tools:'; then
    printf 'fallback Web UI offers the review model a tool surface\n' >&2
    exit 1
fi
# The review holds the same `busy` flag a chat turn holds, so each review and
# each correction is a transition through idle.
grep -F 'async function runImageReview(card, fields, lineage) {' "$fallback_ui" >/dev/null
grep -F 'const REVIEW_OBSERVATION_MAX_CHARS = 300;' "$fallback_ui" >/dev/null
# The correction carries the first approval's seed and adds the review's delta.
grep -F 'seedGenerated: false };' "$fallback_ui" >/dev/null
grep -F 'correction ${correctionNumber} of ${IMAGE_CORRECTION_CAP}; ' "$fallback_ui" >/dev/null
grep -F 'if (lineage.correctionsUsed >= IMAGE_CORRECTION_CAP) {' "$fallback_ui" >/dev/null
grep -F 'const imageOutcome = await approveImageGeneration(bounded, lineage.model, note);' \
    "$fallback_ui" >/dev/null
# The roster decides whether a review is offered at all: GET /props reports the
# vision modality per model, and a text-only roster leaves the button hidden.
grep -F 'async function resolveVisionModel(generation, signal) {' "$fallback_ui" >/dev/null
grep -F 'if (props && props.modalities && props.modalities.vision === true) {' \
    "$fallback_ui" >/dev/null
grep -F 'function forgetVisionModel() {' "$fallback_ui" >/dev/null
grep -F 'const dataUri = await artifactDataUri(lineage.sha256, controller.signal);' \
    "$fallback_ui" >/dev/null
grep -F 'headers: authHeaders(), signal });' "$fallback_ui" >/dev/null
if [ "$(grep -c 'forgetVisionModel();' "$fallback_ui")" -lt 2 ]; then
    printf 'fallback Web UI does not clear the vision-model cache on every roster read\n' >&2
    exit 1
fi
grep -F "reviewButton.className = 'act image-review-button';" "$fallback_ui" >/dev/null
grep -F '  reviewButton.hidden = true;' "$fallback_ui" >/dev/null

printf 'fallback_webui_image_authorization=accepted\n'
